-- ===================================================================
-- SPOTDROP WAITLIST SCHEMA FOR SUPABASE
-- Run this in your Supabase Project -> SQL Editor
-- ===================================================================

CREATE TABLE IF NOT EXISTS public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  source TEXT DEFAULT 'direct',
  referral_code TEXT UNIQUE NOT NULL,
  referred_by TEXT,
  status TEXT DEFAULT 'waitlisted',
  notes TEXT DEFAULT ''
);

-- Performance & Query Indexes
CREATE INDEX IF NOT EXISTS idx_waitlist_email ON public.waitlist(email);
CREATE INDEX IF NOT EXISTS idx_waitlist_referral_code ON public.waitlist(referral_code);
CREATE INDEX IF NOT EXISTS idx_waitlist_created_at ON public.waitlist(created_at);

-- Enable Row Level Security (RLS)
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Allow server backend (using Service Role Key) full access
CREATE POLICY "Full access for service role" ON public.waitlist
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- (Optional) If using Anon key for direct client reads/writes, you can enable these:
CREATE POLICY "Public insert with valid email" ON public.waitlist
  FOR INSERT
  WITH CHECK (email IS NOT NULL AND length(email) > 3);
